ðŸš€ Starting ERPNext Timesheet Setup...
â–¶ Running setup_timesheet.py...
{'data': {'name': 'Custom_Timesheet', 'creation': '2025-03-27 14:20:58.863912', 'modified': '2025-03-27 14:20:58.863912', 'modified_by': 'Administrator', 'owner': 'Administrator', 'docstatus': 0, 'idx': 0, 'issingle': 0, 'is_virtual': 0, 'is_tree': 0, 'istable': 0, 'editable_grid': 1, 'track_changes': 0, 'module': 'Projects', 'naming_rule': '', 'sort_field': 'modified', 'sort_order': 'DESC', 'read_only': 0, 'in_create': 0, 'allow_copy': 0, 'allow_rename': 1, 'allow_import': 0, 'hide_toolbar': 0, 'track_seen': 0, 'max_attachments': 0, 'document_type': '', 'engine': 'InnoDB', 'is_submittable': 0, 'show_name_in_global_search': 0, 'custom': 0, 'beta': 0, 'has_web_view': 0, 'allow_guest_to_view': 0, 'email_append_to': 0, 'show_title_field_in_link': 0, 'translated_doctype': 0, 'is_calendar_and_gantt': 0, 'quick_entry': 0, 'track_views': 0, 'queue_in_background': 0, 'allow_events_in_timeline': 0, 'allow_auto_repeat': 0, 'make_attachments_public': 0, 'force_re_route_to_default_view': 0, 'show_preview_popup': 0, 'index_web_pages_for_search': 1, 'doctype': 'DocType', 'states': [], 'fields': [{'name': 'scpal06iko', 'creation': '2025-03-27 14:20:58.863912', 'modified': '2025-03-27 14:20:58.863912', 'modified_by': 'bassam.ali@moosvi.pk', 'owner': 'bassam.ali@moosvi.pk', 'docstatus': 0, 'parent': 'Custom_Timesheet', 'parentfield': 'fields', 'parenttype': 'DocType', 'idx': 1, 'fieldname': 'project', 'fieldtype': 'Link', 'options': 'Project', 'search_index': 0, 'show_dashboard': 0, 'hidden': 0, 'set_only_once': 0, 'allow_in_quick_entry': 0, 'print_hide': 0, 'report_hide': 0, 'reqd': 0, 'bold': 0, 'in_global_search': 0, 'collapsible': 0, 'unique': 0, 'no_copy': 0, 'allow_on_submit': 0, 'permlevel': 0, 'ignore_user_permissions': 0, 'columns': 0, 'in_list_view': 0, 'fetch_if_empty': 0, 'in_filter': 0, 'remember_last_selected_value': 0, 'ignore_xss_filter': 0, 'print_hide_if_no_value': 0, 'allow_bulk_edit': 0, 'in_standard_filter': 0, 'in_preview': 0, 'read_only': 0, 'precision': '', 'length': 0, 'translatable': 0, 'hide_border': 0, 'hide_days': 0, 'hide_seconds': 0, 'non_negative': 0, 'is_virtual': 0, 'sort_options': 0, 'show_on_timeline': 0, 'make_attachment_public': 0, 'doctype': 'DocField', '__unsaved': 1}, {'name': 'fbcn93njgd', 'creation': '2025-03-27 14:20:58.863912', 'modified': '2025-03-27 14:20:58.863912', 'modified_by': 'bassam.ali@moosvi.pk', 'owner': 'bassam.ali@moosvi.pk', 'docstatus': 0, 'parent': 'Custom_Timesheet', 'parentfield': 'fields', 'parenttype': 'DocType', 'idx': 2, 'fieldname': 'hours_worked', 'fieldtype': 'Float', 'search_index': 0, 'show_dashboard': 0, 'hidden': 0, 'set_only_once': 0, 'allow_in_quick_entry': 0, 'print_hide': 0, 'report_hide': 0, 'reqd': 0, 'bold': 0, 'in_global_search': 0, 'collapsible': 0, 'unique': 0, 'no_copy': 0, 'allow_on_submit': 0, 'permlevel': 0, 'ignore_user_permissions': 0, 'columns': 0, 'in_list_view': 0, 'fetch_if_empty': 0, 'in_filter': 0, 'remember_last_selected_value': 0, 'ignore_xss_filter': 0, 'print_hide_if_no_value': 0, 'allow_bulk_edit': 0, 'in_standard_filter': 0, 'in_preview': 0, 'read_only': 0, 'precision': '', 'length': 0, 'translatable': 0, 'hide_border': 0, 'hide_days': 0, 'hide_seconds': 0, 'non_negative': 0, 'is_virtual': 0, 'sort_options': 0, 'show_on_timeline': 0, 'make_attachment_public': 0, 'doctype': 'DocField', '__unsaved': 1}, {'name': 'in88472uhu', 'creation': '2025-03-27 14:20:58.863912', 'modified': '2025-03-27 14:20:58.863912', 'modified_by': 'bassam.ali@moosvi.pk', 'owner': 'bassam.ali@moosvi.pk', 'docstatus': 0, 'parent': 'Custom_Timesheet', 'parentfield': 'fields', 'parenttype': 'DocType', 'idx': 3, 'fieldname': 'notes', 'fieldtype': 'Text', 'search_index': 0, 'show_dashboard': 0, 'hidden': 0, 'set_only_once': 0, 'allow_in_quick_entry': 0, 'print_hide': 0, 'report_hide': 0, 'reqd': 0, 'bold': 0, 'in_global_search': 0, 'collapsible': 0, 'unique': 0, 'no_copy': 0, 'allow_on_submit': 0, 'permlevel': 0, 'ignore_user_permissions': 0, 'columns': 0, 'in_list_view': 0, 'fetch_if_empty': 0, 'in_filter': 0, 'remember_last_selected_value': 0, 'ignore_xss_filter': 0, 'print_hide_if_no_value': 0, 'allow_bulk_edit': 0, 'in_standard_filter': 0, 'in_preview': 0, 'read_only': 0, 'precision': '', 'length': 0, 'translatable': 0, 'hide_border': 0, 'hide_days': 0, 'hide_seconds': 0, 'non_negative': 0, 'is_virtual': 0, 'sort_options': 0, 'show_on_timeline': 0, 'make_attachment_public': 0, 'doctype': 'DocField', '__unsaved': 1}, {'name': '227ht00ab8', 'creation': '2025-03-27 14:20:58.863912', 'modified': '2025-03-27 14:20:58.863912', 'modified_by': 'bassam.ali@moosvi.pk', 'owner': 'bassam.ali@moosvi.pk', 'docstatus': 0, 'parent': 'Custom_Timesheet', 'parentfield': 'fields', 'parenttype': 'DocType', 'idx': 4, 'fieldname': 'status', 'fieldtype': 'Select', 'options': 'Draft\\nSubmitted\\nApproved', 'search_index': 0, 'show_dashboard': 0, 'hidden': 0, 'set_only_once': 0, 'allow_in_quick_entry': 0, 'print_hide': 0, 'report_hide': 0, 'reqd': 0, 'bold': 0, 'in_global_search': 0, 'collapsible': 0, 'unique': 0, 'no_copy': 0, 'allow_on_submit': 0, 'permlevel': 0, 'ignore_user_permissions': 0, 'columns': 0, 'in_list_view': 0, 'fetch_if_empty': 0, 'in_filter': 0, 'remember_last_selected_value': 0, 'ignore_xss_filter': 0, 'print_hide_if_no_value': 0, 'allow_bulk_edit': 0, 'in_standard_filter': 0, 'in_preview': 0, 'read_only': 0, 'precision': '', 'length': 0, 'translatable': 0, 'hide_border': 0, 'hide_days': 0, 'hide_seconds': 0, 'non_negative': 0, 'is_virtual': 0, 'sort_options': 0, 'show_on_timeline': 0, 'make_attachment_public': 0, 'doctype': 'DocField', '__unsaved': 1}, {'name': 'hlcj4v7vjr', 'creation': '2025-03-27 14:20:58.863912', 'modified': '2025-03-27 14:20:58.863912', 'modified_by': 'bassam.ali@moosvi.pk', 'owner': 'bassam.ali@moosvi.pk', 'docstatus': 0, 'parent': 'Custom_Timesheet', 'parentfield': 'fields', 'parenttype': 'DocType', 'idx': 5, 'fieldname': 'locked', 'fieldtype': 'Check', 'search_index': 0, 'show_dashboard': 0, 'hidden': 0, 'set_only_once': 0, 'allow_in_quick_entry': 0, 'print_hide': 0, 'report_hide': 0, 'reqd': 0, 'bold': 0, 'in_global_search': 0, 'collapsible': 0, 'unique': 0, 'no_copy': 0, 'allow_on_submit': 0, 'permlevel': 0, 'ignore_user_permissions': 0, 'columns': 0, 'default': '0', 'in_list_view': 0, 'fetch_if_empty': 0, 'in_filter': 0, 'remember_last_selected_value': 0, 'ignore_xss_filter': 0, 'print_hide_if_no_value': 0, 'allow_bulk_edit': 0, 'in_standard_filter': 0, 'in_preview': 0, 'read_only': 0, 'precision': '', 'length': 0, 'translatable': 0, 'hide_border': 0, 'hide_days': 0, 'hide_seconds': 0, 'non_negative': 0, 'is_virtual': 0, 'sort_options': 0, 'show_on_timeline': 0, 'make_attachment_public': 0, 'doctype': 'DocField', '__unsaved': 1}, {'name': 'e0a0bt0mh7', 'creation': '2025-03-27 14:20:58.863912', 'modified': '2025-03-27 14:20:58.863912', 'modified_by': 'bassam.ali@moosvi.pk', 'owner': 'bassam.ali@moosvi.pk', 'docstatus': 0, 'parent': 'Custom_Timesheet', 'parentfield': 'fields', 'parenttype': 'DocType', 'idx': 6, 'fieldname': 'employee', 'fieldtype': 'Link', 'options': 'Employee', 'search_index': 0, 'show_dashboard': 0, 'hidden': 0, 'set_only_once': 0, 'allow_in_quick_entry': 0, 'print_hide': 0, 'report_hide': 0, 'reqd': 0, 'bold': 0, 'in_global_search': 0, 'collapsible': 0, 'unique': 0, 'no_copy': 0, 'allow_on_submit': 0, 'permlevel': 0, 'ignore_user_permissions': 0, 'columns': 0, 'in_list_view': 0, 'fetch_if_empty': 0, 'in_filter': 0, 'remember_last_selected_value': 0, 'ignore_xss_filter': 0, 'print_hide_if_no_value': 0, 'allow_bulk_edit': 0, 'in_standard_filter': 0, 'in_preview': 0, 'read_only': 0, 'precision': '', 'length': 0, 'translatable': 0, 'hide_border': 0, 'hide_days': 0, 'hide_seconds': 0, 'non_negative': 0, 'is_virtual': 0, 'sort_options': 0, 'show_on_timeline': 0, 'make_attachment_public': 0, 'doctype': 'DocField', '__unsaved': 1}], 'actions': [], 'links': [], 'permissions': []}}
{"exception":"frappe.exceptions.LinkValidationError: Could not find Row #2: State: Pending Approval, Row #1: Next State: Pending Approval, Row #2: State: Pending Approval","exc_type":"LinkValidationError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 114, in application\\n    response = frappe.api.handle(request)\\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n           ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 287, in insert\\n    self._validate_links()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 942, in _validate_links\\n    frappe.throw(_(\\\"Could not find {0}\\\").format(msg), frappe.LinkValidationError)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 603, in throw\\n    msgprint(\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 568, in msgprint\\n    _raise_exception()\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 519, in _raise_exception\\n    raise exc\\nfrappe.exceptions.LinkValidationError: Could not find Row #2: State: Pending Approval, Row #1: Next State: Pending Approval, Row #2: State: Pending Approval\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"Could not find Row #2: State: Pending Approval, Row #1: Next State: Pending Approval, Row #2: State: Pending Approval\\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1, \\\"__frappe_exc_id\\\": \\\"d31bd78a4d75191352f6c4b26730945ce5fd5187bdeb436b739a459f\\\"}\"]"}
â–¶ Running setup_projects.py...
{'data': {'name': 'PROJ-0002', 'owner': 'bassam.ali@moosvi.pk', 'creation': '2025-03-27 14:20:59.456956', 'modified': '2025-03-27 14:20:59.456956', 'modified_by': 'bassam.ali@moosvi.pk', 'docstatus': 0, 'idx': 0, 'naming_series': 'PROJ-.####', 'project_name': 'Project A', 'status': 'Open', 'is_active': 'Yes', 'percent_complete_method': 'Task Completion', 'percent_complete': 0.0, 'priority': 'Medium', 'actual_time': 0.0, 'estimated_costing': 0.0, 'total_costing_amount': 0.0, 'total_purchase_cost': 0.0, 'company': 'Moosvi Dev Concepts', 'total_sales_amount': 0.0, 'total_billable_amount': 0.0, 'total_billed_amount': 0.0, 'total_consumed_material_cost': 0.0, 'gross_margin': 0.0, 'per_gross_margin': 0.0, 'collect_progress': 0, 'frequency': 'Hourly', 'from_time': '14:20:59.442941', 'to_time': '14:20:59.443164', 'first_email': '14:20:59.443185', 'second_email': '14:20:59.443212', 'daily_time_to_send': '14:20:59.443226', 'day_to_send': 'Monday', 'weekly_time_to_send': '14:20:59.443240', 'doctype': 'Project', 'users': []}}
{'data': {'name': 'PROJ-0003', 'owner': 'bassam.ali@moosvi.pk', 'creation': '2025-03-27 14:20:59.660098', 'modified': '2025-03-27 14:20:59.660098', 'modified_by': 'bassam.ali@moosvi.pk', 'docstatus': 0, 'idx': 0, 'naming_series': 'PROJ-.####', 'project_name': 'Project B', 'status': 'Open', 'is_active': 'Yes', 'percent_complete_method': 'Task Completion', 'percent_complete': 0.0, 'priority': 'Medium', 'actual_time': 0.0, 'estimated_costing': 0.0, 'total_costing_amount': 0.0, 'total_purchase_cost': 0.0, 'company': 'Moosvi Dev Concepts', 'total_sales_amount': 0.0, 'total_billable_amount': 0.0, 'total_billed_amount': 0.0, 'total_consumed_material_cost': 0.0, 'gross_margin': 0.0, 'per_gross_margin': 0.0, 'collect_progress': 0, 'frequency': 'Hourly', 'from_time': '14:20:59.657899', 'to_time': '14:20:59.658157', 'first_email': '14:20:59.658182', 'second_email': '14:20:59.658200', 'daily_time_to_send': '14:20:59.658217', 'day_to_send': 'Monday', 'weekly_time_to_send': '14:20:59.658234', 'doctype': 'Project', 'users': []}}
{"exception":"frappe.exceptions.LinkValidationError: Could not find User: employee1@example.com, For Value: PROJ001","exc_type":"LinkValidationError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 114, in application\\n    response = frappe.api.handle(request)\\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n           ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 287, in insert\\n    self._validate_links()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 942, in _validate_links\\n    frappe.throw(_(\\\"Could not find {0}\\\").format(msg), frappe.LinkValidationError)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 603, in throw\\n    msgprint(\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 568, in msgprint\\n    _raise_exception()\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 519, in _raise_exception\\n    raise exc\\nfrappe.exceptions.LinkValidationError: Could not find User: employee1@example.com, For Value: PROJ001\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"Could not find User: employee1@example.com, For Value: PROJ001\\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1, \\\"__frappe_exc_id\\\": \\\"a5c344f80ea9c1e2cb91205cdabd388c96e50090c6b81710e354865d\\\"}\"]"}
{"exception":"frappe.exceptions.LinkValidationError: Could not find User: employee2@example.com, For Value: PROJ002","exc_type":"LinkValidationError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 114, in application\\n    response = frappe.api.handle(request)\\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n           ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 287, in insert\\n    self._validate_links()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 942, in _validate_links\\n    frappe.throw(_(\\\"Could not find {0}\\\").format(msg), frappe.LinkValidationError)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 603, in throw\\n    msgprint(\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 568, in msgprint\\n    _raise_exception()\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 519, in _raise_exception\\n    raise exc\\nfrappe.exceptions.LinkValidationError: Could not find User: employee2@example.com, For Value: PROJ002\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"Could not find User: employee2@example.com, For Value: PROJ002\\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1, \\\"__frappe_exc_id\\\": \\\"57b7f98d6ee74e1e7d6e16ea7549add5d562610a2d431ff6d462c7e9\\\"}\"]"}
â–¶ Running setup_permissions.py...
{"exception":"frappe.exceptions.DuplicateEntryError: ('Module Def', 'Projects', IntegrityError(1062, \"Duplicate entry 'Projects' for key 'PRIMARY'\"))","exc_type":"DuplicateEntryError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 564, in db_insert\\n    frappe.db.sql(\\n  File \\\"apps/frappe/frappe/database/database.py\\\", line 230, in sql\\n    self._cursor.execute(query, values)\\n  File \\\"env/lib/python3.12/site-packages/pymysql/cursors.py\\\", line 153, in execute\\n    result = self._query(query)\\n             ^^^^^^^^^^^^^^^^^^\\n  File \\\"env/lib/python3.12/site-packages/pymysql/cursors.py\\\", line 322, in _query\\n    conn.query(q)\\n  File \\\"env/lib/python3.12/site-packages/pymysql/connections.py\\\", line 563, in query\\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"env/lib/python3.12/site-packages/pymysql/connections.py\\\", line 825, in _read_query_result\\n    result.read()\\n  File \\\"env/lib/python3.12/site-packages/pymysql/connections.py\\\", line 1199, in read\\n    first_packet = self.connection._read_packet()\\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"env/lib/python3.12/site-packages/pymysql/connections.py\\\", line 775, in _read_packet\\n    packet.raise_for_error()\\n  File \\\"env/lib/python3.12/site-packages/pymysql/protocol.py\\\", line 219, in raise_for_error\\n    err.raise_mysql_exception(self._data)\\n  File \\\"env/lib/python3.12/site-packages/pymysql/err.py\\\", line 150, in raise_mysql_exception\\n    raise errorclass(errno, errval)\\npymysql.err.IntegrityError: (1062, \\\"Duplicate entry 'Projects' for key 'PRIMARY'\\\")\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 114, in application\\n    response = frappe.api.handle(request)\\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n           ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 306, in insert\\n    self.db_insert(ignore_if_duplicate=ignore_if_duplicate)\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 591, in db_insert\\n    raise frappe.DuplicateEntryError(self.doctype, self.name, e)\\nfrappe.exceptions.DuplicateEntryError: ('Module Def', 'Projects', IntegrityError(1062, \\\"Duplicate entry 'Projects' for key 'PRIMARY'\\\"))\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"Module Def <strong>Projects</strong> already exists\\\", \\\"title\\\": \\\"Duplicate Name\\\", \\\"indicator\\\": \\\"red\\\"}\"]"}
{"exception":"Error: No module named 'frappe.core.doctype.role_permission'","exc_type":"ImportError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/modules/utils.py\\\", line 254, in load_doctype_module\\n    doctype_python_modules[key] = frappe.get_module(module_name)\\n                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1434, in get_module\\n    return importlib.import_module(modulename)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"/usr/lib/python3.12/importlib/__init__.py\\\", line 90, in import_module\\n    return _bootstrap._gcd_import(name[level:], package, level)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1387, in _gcd_import\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1360, in _find_and_load\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1310, in _find_and_load_unlocked\\n  File \\\"<frozen importlib._bootstrap>\\\", line 488, in _call_with_frames_removed\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1387, in _gcd_import\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1360, in _find_and_load\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1324, in _find_and_load_unlocked\\nModuleNotFoundError: No module named 'frappe.core.doctype.role_permission'\\n\\nThe above exception was the direct cause of the following exception:\\n\\nTraceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 114, in application\\n    response = frappe.api.handle(request)\\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n           ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1148, in new_doc\\n    new_doc = get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)\\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/create_new.py\\\", line 22, in get_new_doc\\n    frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)\\n                                              ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/create_new.py\\\", line 35, in make_new_doc\\n    doc = frappe.get_doc({\\\"doctype\\\": doctype, \\\"__islocal\\\": 1, \\\"owner\\\": frappe.session.user, \\\"docstatus\\\": 0})\\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1291, in get_doc\\n    doc = frappe.model.document.get_doc(*args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 83, in get_doc\\n    controller = get_controller(doctype)\\n                 ^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 71, in get_controller\\n    site_controllers[doctype] = import_controller(doctype)\\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 96, in import_controller\\n    module = load_doctype_module(doctype, module_name)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/modules/utils.py\\\", line 258, in load_doctype_module\\n    raise ImportError(msg) from e\\nImportError: Module import failed for Role Permission, the DocType you're trying to open might be deleted.\\nError: No module named 'frappe.core.doctype.role_permission'\\n\"]"}
â–¶ Running setup_dashboard.py...
{"exception":"frappe.exceptions.LinkValidationError: Could not find Link To: Custom_Timesheet","exc_type":"LinkValidationError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 114, in application\\n    response = frappe.api.handle(request)\\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n           ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 287, in insert\\n    self._validate_links()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 942, in _validate_links\\n    frappe.throw(_(\\\"Could not find {0}\\\").format(msg), frappe.LinkValidationError)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 603, in throw\\n    msgprint(\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 568, in msgprint\\n    _raise_exception()\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 519, in _raise_exception\\n    raise exc\\nfrappe.exceptions.LinkValidationError: Could not find Link To: Custom_Timesheet\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"Could not find Link To: Custom_Timesheet\\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1, \\\"__frappe_exc_id\\\": \\\"83caebe28f679d01bf634c85edf18c534a9d6b6d820e27ceb4a113d4\\\"}\"]","_debug_messages":"[\"Error in query:\\n('SELECT `name` FROM `tabdoctype` WHERE `name`=%(param1)s ORDER BY `modified` DESC LIMIT 1', {'param1': 'Custom_Timesheet'})\"]"}
{"exception":"frappe.exceptions.DuplicateEntryError: ('Module Def', 'Projects', IntegrityError(1062, \"Duplicate entry 'Projects' for key 'PRIMARY'\"))","exc_type":"DuplicateEntryError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 564, in db_insert\\n    frappe.db.sql(\\n  File \\\"apps/frappe/frappe/database/database.py\\\", line 230, in sql\\n    self._cursor.execute(query, values)\\n  File \\\"env/lib/python3.12/site-packages/pymysql/cursors.py\\\", line 153, in execute\\n    result = self._query(query)\\n             ^^^^^^^^^^^^^^^^^^\\n  File \\\"env/lib/python3.12/site-packages/pymysql/cursors.py\\\", line 322, in _query\\n    conn.query(q)\\n  File \\\"env/lib/python3.12/site-packages/pymysql/connections.py\\\", line 563, in query\\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"env/lib/python3.12/site-packages/pymysql/connections.py\\\", line 825, in _read_query_result\\n    result.read()\\n  File \\\"env/lib/python3.12/site-packages/pymysql/connections.py\\\", line 1199, in read\\n    first_packet = self.connection._read_packet()\\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"env/lib/python3.12/site-packages/pymysql/connections.py\\\", line 775, in _read_packet\\n    packet.raise_for_error()\\n  File \\\"env/lib/python3.12/site-packages/pymysql/protocol.py\\\", line 219, in raise_for_error\\n    err.raise_mysql_exception(self._data)\\n  File \\\"env/lib/python3.12/site-packages/pymysql/err.py\\\", line 150, in raise_mysql_exception\\n    raise errorclass(errno, errval)\\npymysql.err.IntegrityError: (1062, \\\"Duplicate entry 'Projects' for key 'PRIMARY'\\\")\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 114, in application\\n    response = frappe.api.handle(request)\\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n           ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 306, in insert\\n    self.db_insert(ignore_if_duplicate=ignore_if_duplicate)\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 591, in db_insert\\n    raise frappe.DuplicateEntryError(self.doctype, self.name, e)\\nfrappe.exceptions.DuplicateEntryError: ('Module Def', 'Projects', IntegrityError(1062, \\\"Duplicate entry 'Projects' for key 'PRIMARY'\\\"))\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"Module Def <strong>Projects</strong> already exists\\\", \\\"title\\\": \\\"Duplicate Name\\\", \\\"indicator\\\": \\\"red\\\"}\"]"}
â–¶ Running setup_ui.py...
{"exception":"frappe.exceptions.DuplicateEntryError: ('Website Theme', 'Unanet Theme', IntegrityError(1062, \"Duplicate entry 'Unanet Theme' for key 'PRIMARY'\"))","exc_type":"DuplicateEntryError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 564, in db_insert\\n    frappe.db.sql(\\n  File \\\"apps/frappe/frappe/database/database.py\\\", line 230, in sql\\n    self._cursor.execute(query, values)\\n  File \\\"env/lib/python3.12/site-packages/pymysql/cursors.py\\\", line 153, in execute\\n    result = self._query(query)\\n             ^^^^^^^^^^^^^^^^^^\\n  File \\\"env/lib/python3.12/site-packages/pymysql/cursors.py\\\", line 322, in _query\\n    conn.query(q)\\n  File \\\"env/lib/python3.12/site-packages/pymysql/connections.py\\\", line 563, in query\\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"env/lib/python3.12/site-packages/pymysql/connections.py\\\", line 825, in _read_query_result\\n    result.read()\\n  File \\\"env/lib/python3.12/site-packages/pymysql/connections.py\\\", line 1199, in read\\n    first_packet = self.connection._read_packet()\\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"env/lib/python3.12/site-packages/pymysql/connections.py\\\", line 775, in _read_packet\\n    packet.raise_for_error()\\n  File \\\"env/lib/python3.12/site-packages/pymysql/protocol.py\\\", line 219, in raise_for_error\\n    err.raise_mysql_exception(self._data)\\n  File \\\"env/lib/python3.12/site-packages/pymysql/err.py\\\", line 150, in raise_mysql_exception\\n    raise errorclass(errno, errval)\\npymysql.err.IntegrityError: (1062, \\\"Duplicate entry 'Unanet Theme' for key 'PRIMARY'\\\")\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 114, in application\\n    response = frappe.api.handle(request)\\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n           ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 306, in insert\\n    self.db_insert(ignore_if_duplicate=ignore_if_duplicate)\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 591, in db_insert\\n    raise frappe.DuplicateEntryError(self.doctype, self.name, e)\\nfrappe.exceptions.DuplicateEntryError: ('Website Theme', 'Unanet Theme', IntegrityError(1062, \\\"Duplicate entry 'Unanet Theme' for key 'PRIMARY'\\\"))\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"Compiled Successfully\\\", \\\"title\\\": \\\"Message\\\", \\\"alert\\\": 1}\", \"{\\\"message\\\": \\\"Website Theme <strong>Unanet Theme</strong> already exists\\\", \\\"title\\\": \\\"Duplicate Name\\\", \\\"indicator\\\": \\\"red\\\"}\"]"}
{"exception":"Error: No module named 'frappe.core.doctype.custom_script'","exc_type":"ImportError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/modules/utils.py\\\", line 254, in load_doctype_module\\n    doctype_python_modules[key] = frappe.get_module(module_name)\\n                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1434, in get_module\\n    return importlib.import_module(modulename)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"/usr/lib/python3.12/importlib/__init__.py\\\", line 90, in import_module\\n    return _bootstrap._gcd_import(name[level:], package, level)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1387, in _gcd_import\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1360, in _find_and_load\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1310, in _find_and_load_unlocked\\n  File \\\"<frozen importlib._bootstrap>\\\", line 488, in _call_with_frames_removed\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1387, in _gcd_import\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1360, in _find_and_load\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1324, in _find_and_load_unlocked\\nModuleNotFoundError: No module named 'frappe.core.doctype.custom_script'\\n\\nThe above exception was the direct cause of the following exception:\\n\\nTraceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 114, in application\\n    response = frappe.api.handle(request)\\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n           ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1148, in new_doc\\n    new_doc = get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)\\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/create_new.py\\\", line 22, in get_new_doc\\n    frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)\\n                                              ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/create_new.py\\\", line 35, in make_new_doc\\n    doc = frappe.get_doc({\\\"doctype\\\": doctype, \\\"__islocal\\\": 1, \\\"owner\\\": frappe.session.user, \\\"docstatus\\\": 0})\\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1291, in get_doc\\n    doc = frappe.model.document.get_doc(*args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 83, in get_doc\\n    controller = get_controller(doctype)\\n                 ^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 71, in get_controller\\n    site_controllers[doctype] = import_controller(doctype)\\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 96, in import_controller\\n    module = load_doctype_module(doctype, module_name)\\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/modules/utils.py\\\", line 258, in load_doctype_module\\n    raise ImportError(msg) from e\\nImportError: Module import failed for Custom Script, the DocType you're trying to open might be deleted.\\nError: No module named 'frappe.core.doctype.custom_script'\\n\"]"}
âœ… ERPNext Timesheet Setup Completed Successfully!
